//! Timeout-aware command execution utility.

use std::io::Read as _;
use std::process::{Command, ExitStatus, Output, Stdio};
use std::time::{Duration, Instant};

#[cfg(unix)]
use std::os::unix::process::ExitStatusExt as _;
#[cfg(windows)]
use std::os::windows::process::ExitStatusExt as _;
use tracing::warn;

/// Exit code used when a command is terminated due to timeout.
pub(crate) const TIMEOUT_EXIT_CODE: i32 = 124;

/// Prefix used in stderr when a command times out.
const TIMEOUT_STDERR_PREFIX: &str = "[Command timed out after";

/// Command output with timeout metadata.
pub struct TimedOutput {
    /// Captured process output.
    pub output: Output,
    /// True when the process was killed due to timeout by `run_with_timeout_tracked`.
    pub timed_out: bool,
}

#[cfg(unix)]
fn timeout_exit_status() -> ExitStatus {
    // Unix wait status encodes the exit code in the high byte.
    ExitStatus::from_raw(TIMEOUT_EXIT_CODE << 8)
}

#[cfg(windows)]
fn timeout_exit_status() -> ExitStatus {
    ExitStatus::from_raw(TIMEOUT_EXIT_CODE as u32)
}

#[cfg(test)]
/// Returns true when output corresponds to a timeout generated by `run_with_timeout`.
pub fn is_timeout_output(output: &Output) -> bool {
    output.status.code() == Some(TIMEOUT_EXIT_CODE)
        && output.stderr.starts_with(TIMEOUT_STDERR_PREFIX.as_bytes())
}

/// Execute a command with a timeout and return timeout metadata.
///
/// For callers that only need `Output`, use `run_with_timeout`.
pub fn run_with_timeout_tracked(
    mut child: std::process::Child,
    timeout_secs: u64,
    command_desc: &str,
) -> Result<TimedOutput, String> {
    // Take ownership of stdout/stderr handles for reading in threads
    let stdout_handle = child.stdout.take();
    let stderr_handle = child.stderr.take();

    // Read stdout in a thread (prevents pipe buffer deadlock)
    let stdout_thread = std::thread::spawn(move || {
        let mut buf = Vec::new();
        if let Some(mut stdout) = stdout_handle {
            stdout.read_to_end(&mut buf).ok();
        }
        buf
    });

    // Read stderr in a thread
    let stderr_thread = std::thread::spawn(move || {
        let mut buf = Vec::new();
        if let Some(mut stderr) = stderr_handle {
            stderr.read_to_end(&mut buf).ok();
        }
        buf
    });

    // Wait for child with timeout using try_wait polling
    let deadline = Instant::now() + Duration::from_secs(timeout_secs);
    let (status, timed_out) = loop {
        match child.try_wait() {
            Ok(Some(status)) => break (status, false),
            Ok(None) => {
                if Instant::now() >= deadline {
                    warn!(
                        "⏰ Command timed out after {}s: {}",
                        timeout_secs, command_desc
                    );
                    // Kill the child process (sends SIGKILL on Unix)
                    let _ = child.kill();
                    // Reap the zombie process
                    let _ = child.wait();
                    warn!("💀 Process killed (SIGKILL): {}", command_desc);
                    break (timeout_exit_status(), true);
                }
                std::thread::sleep(Duration::from_millis(100));
            }
            Err(e) => {
                return Err(format!(
                    "Failed to wait for command '{}': {}",
                    command_desc, e
                ));
            }
        }
    };

    if timed_out {
        // Don't join reader threads: child subprocesses (e.g. sh → sleep) may still
        // hold pipe handles open, causing join() to block indefinitely.
        // The threads will be cleaned up when the process exits.
        let msg = format!(
            "{} {}s: {}]\n",
            TIMEOUT_STDERR_PREFIX, timeout_secs, command_desc
        );
        return Ok(TimedOutput {
            output: Output {
                status,
                stdout: Vec::new(),
                stderr: msg.into_bytes(),
            },
            timed_out: true,
        });
    }

    // Collect output from reader threads (finish quickly after normal process exit)
    let stdout = stdout_thread.join().unwrap_or_default();
    let stderr = stderr_thread.join().unwrap_or_default();

    Ok(TimedOutput {
        output: Output {
            status,
            stdout,
            stderr,
        },
        timed_out: false,
    })
}

/// Execute a command with a timeout.
///
/// Spawns the command with piped stdout/stderr, reads output in separate threads
/// (to prevent pipe buffer deadlock), and polls `try_wait` until the child exits
/// or the deadline is reached. On timeout, the child process is killed (SIGKILL)
/// and reaped. Timeout returns exit code 124.
pub fn run_with_timeout(
    child: std::process::Child,
    timeout_secs: u64,
    command_desc: &str,
) -> Result<Output, String> {
    run_with_timeout_tracked(child, timeout_secs, command_desc).map(|result| result.output)
}

/// Spawn a command with piped stdout/stderr and additional environment variables.
/// Used by stop hooks to propagate loop prevention env vars to child processes.
pub fn spawn_piped_with_env(
    program: &str,
    args: &[String],
    envs: &[(&str, &str)],
) -> Result<std::process::Child, String> {
    let mut cmd = if cfg!(target_os = "windows") {
        let mut c = Command::new("cmd");
        c.arg("/c").arg(program).args(args);
        c
    } else {
        let mut c = Command::new(program);
        c.args(args);
        c
    };
    cmd.stdout(Stdio::piped()).stderr(Stdio::piped());
    for &(key, value) in envs {
        cmd.env(key, value);
    }
    cmd.spawn()
        .map_err(|e| format!("Failed to execute '{}': {}", program, e))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test helper: spawn without extra env vars.
    fn spawn_piped(program: &str, args: &[String]) -> Result<std::process::Child, String> {
        spawn_piped_with_env(program, args, &[])
    }

    // === spawn_piped tests ===

    #[test]
    fn test_spawn_piped_valid_command() {
        let child = spawn_piped("echo", &["hello".to_string()]);
        assert!(child.is_ok(), "Should spawn valid command");
        // Reap the child
        let _ = child.unwrap().wait();
    }

    #[test]
    fn test_spawn_piped_nonexistent_command() {
        let child = spawn_piped("nonexistent-command-xyz-abc-999", &[]);
        assert!(child.is_err(), "Should fail for nonexistent command");
        assert!(
            child.unwrap_err().contains("Failed to execute"),
            "Error should indicate execution failure"
        );
    }

    // === run_with_timeout tests ===

    #[test]
    fn test_run_with_timeout_captures_stdout() {
        let child = spawn_piped("echo", &["hello-stdout".to_string()]).unwrap();
        let output = run_with_timeout(child, 10, "echo hello-stdout").unwrap();

        assert!(output.status.success());
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            stdout.contains("hello-stdout"),
            "Should capture stdout, got: {}",
            stdout
        );
    }

    #[test]
    fn test_run_with_timeout_captures_stderr() {
        let child = spawn_piped(
            "sh",
            &["-c".to_string(), "echo hello-stderr >&2".to_string()],
        )
        .unwrap();
        let output = run_with_timeout(child, 10, "echo stderr").unwrap();

        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("hello-stderr"),
            "Should capture stderr, got: {}",
            stderr
        );
    }

    #[test]
    fn test_run_with_timeout_captures_both_stdout_and_stderr() {
        let child = spawn_piped(
            "sh",
            &[
                "-c".to_string(),
                "echo out-data; echo err-data >&2".to_string(),
            ],
        )
        .unwrap();
        let output = run_with_timeout(child, 10, "both streams").unwrap();

        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(stdout.contains("out-data"), "stdout: {}", stdout);
        assert!(stderr.contains("err-data"), "stderr: {}", stderr);
    }

    #[test]
    fn test_run_with_timeout_nonzero_exit_code() {
        let child = spawn_piped("sh", &["-c".to_string(), "exit 42".to_string()]).unwrap();
        let output = run_with_timeout(child, 10, "exit 42").unwrap();

        assert!(!output.status.success());
        assert_eq!(output.status.code(), Some(42));
    }

    #[test]
    fn test_run_with_timeout_kills_on_timeout() {
        let child = spawn_piped("sleep", &["30".to_string()]).unwrap();
        let pid = child.id();

        let start = Instant::now();
        let result = run_with_timeout(child, 1, "sleep 30");
        let elapsed = start.elapsed();

        assert!(result.is_ok(), "Timeout should return Ok");
        let output = result.unwrap();
        assert!(
            !output.status.success(),
            "Timeout should be treated as failure"
        );
        assert_eq!(
            output.status.code(),
            Some(TIMEOUT_EXIT_CODE),
            "Timeout should use exit code 124"
        );
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("timed out"),
            "Stderr should contain timeout notice: {}",
            stderr
        );
        // stdout is empty on timeout (reader threads are not joined)
        assert!(
            output.stdout.is_empty(),
            "Stdout should be empty on timeout"
        );
        assert!(
            elapsed.as_secs() < 5,
            "Should timeout quickly, took {:?}",
            elapsed
        );
        assert!(is_timeout_output(&output));

        // Verify process is actually dead by checking /proc (Linux) or kill -0 via shell
        #[cfg(unix)]
        {
            let check = Command::new("kill").args(["-0", &pid.to_string()]).output();
            if let Ok(output) = check {
                assert!(
                    !output.status.success(),
                    "Process {} should be dead after timeout kill",
                    pid
                );
            }
        }
    }

    #[test]
    fn test_run_with_timeout_large_output_no_deadlock() {
        // Generate >64KB of output (typical pipe buffer size) to verify no deadlock
        let child = spawn_piped(
            "sh",
            &[
                "-c".to_string(),
                "dd if=/dev/zero bs=1024 count=128 2>/dev/null | tr '\\0' 'A'".to_string(),
            ],
        )
        .unwrap();

        let start = Instant::now();
        let output = run_with_timeout(child, 10, "large output");
        let elapsed = start.elapsed();

        assert!(output.is_ok(), "Should not deadlock on large output");
        assert!(
            elapsed.as_secs() < 10,
            "Should complete quickly, took {:?}",
            elapsed
        );
        let out = output.unwrap();
        assert!(
            out.stdout.len() >= 128 * 1024,
            "Should capture all output: {} bytes",
            out.stdout.len()
        );
    }

    #[test]
    fn test_run_with_timeout_fast_command_under_timeout() {
        let child = spawn_piped("true", &[]).unwrap();
        let start = Instant::now();
        let result = run_with_timeout(child, 60, "true");
        let elapsed = start.elapsed();

        assert!(result.is_ok());
        assert!(result.unwrap().status.success());
        assert!(
            elapsed.as_secs() < 2,
            "Fast command should return quickly: {:?}",
            elapsed
        );
    }

    #[test]
    fn test_is_timeout_output_false_for_normal_exit_124() {
        let child = spawn_piped(
            "sh",
            &[
                "-c".to_string(),
                "echo normal-error >&2; exit 124".to_string(),
            ],
        )
        .unwrap();
        let output = run_with_timeout(child, 10, "exit 124").unwrap();
        assert!(!is_timeout_output(&output));
        assert_eq!(output.status.code(), Some(TIMEOUT_EXIT_CODE));
    }
}
